apiVersion: v1
kind: Service
metadata:
  name: helloworld-db-service
spec:
  ports:
  - port: 3000
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld-db
  type: LoadBalancer
